QUESTION_BANK = {
    "HR": [
        {
            "question": "Tell me about yourself.",
            "keywords": ["background", "skills", "projects", "goals"],
            "hint": "Give a short background, mention your strongest technical skills, highlight one project, and connect it to your career goal.",
            "difficulty": "Easy",
            "target_role": "Software Engineer",
        },
        {
            "question": "Why should we hire you for this role?",
            "keywords": ["problem solving", "technical skills", "teamwork", "impact"],
            "hint": "Show how your skills match the role and explain the value you can bring to the team.",
            "difficulty": "Medium",
            "target_role": "Software Engineer",
        },
        {
            "question": "Describe a time you handled a challenge.",
            "keywords": ["situation", "action", "result", "learning"],
            "hint": "Use a STAR-style answer and end with what you learned from the challenge.",
            "difficulty": "Medium",
            "target_role": "Data Scientist",
        },
        {
            "question": "Tell me about a time you failed and what you learned from it.",
            "keywords": ["failure", "learning", "improvement", "responsibility"],
            "hint": "Be honest about the failure, explain how you handled it, and focus on what you learned.",
            "difficulty": "Medium",
            "target_role": "DevOps Engineer",
        },
        {
            "question": "How do you handle working with someone difficult or different viewpoints?",
            "keywords": ["collaboration", "communication", "respect", "compromise"],
            "hint": "Show maturity by discussing listening, understanding, and finding common ground.",
            "difficulty": "Medium",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "Where do you see yourself in 5 years?",
            "keywords": ["growth", "career goals", "learning", "advancement"],
            "hint": "Be specific about your goals while showing alignment with the company's values.",
            "difficulty": "Easy",
            "target_role": "Backend Developer",
        },
        {
            "question": "What motivates you in your work?",
            "keywords": ["passion", "impact", "learning", "problem solving"],
            "hint": "Connect your motivation to the role and company mission.",
            "difficulty": "Easy",
            "target_role": "Frontend Developer",
        },
        {
            "question": "How do you handle deadline pressure and changing requirements?",
            "keywords": ["adaptability", "prioritization", "communication", "flexibility"],
            "hint": "Show examples of how you manage stress and stay productive.",
            "difficulty": "Medium",
            "target_role": "Systems Engineer",
        },
        {
            "question": "Tell me about a time you led a project or mentored someone.",
            "keywords": ["leadership", "mentoring", "initiative", "responsibility"],
            "hint": "Highlight your leadership style and positive impact on others.",
            "difficulty": "Medium",
            "target_role": "Software Engineer",
        },
        {
            "question": "What is your approach to continuous learning and staying updated with technology?",
            "keywords": ["learning", "growth mindset", "initiative", "curiosity"],
            "hint": "Share specific examples of courses, projects, or communities you engage with.",
            "difficulty": "Easy",
            "target_role": "Data Scientist",
        },
    ],
    "DSA": [
        {
            "question": "How would you explain the difference between an array and a linked list?",
            "keywords": ["memory", "access time", "insertion", "deletion"],
            "hint": "Compare storage style, time complexity, and practical tradeoffs.",
            "difficulty": "Easy",
            "target_role": "Software Engineer",
        },
        {
            "question": "How do you optimize a nested-loop solution?",
            "keywords": ["time complexity", "hashing", "two pointers", "tradeoff"],
            "hint": "Explain how you first analyze complexity, then choose a better data structure or technique.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "When would you use a stack in a real problem?",
            "keywords": ["LIFO", "backtracking", "parsing", "history"],
            "hint": "Mention both the core idea and at least one practical use case.",
            "difficulty": "Medium",
            "target_role": "Software Engineer",
        },
        {
            "question": "Explain the concept of binary search and when you can apply it.",
            "keywords": ["sorted", "divide and conquer", "log n", "precondition"],
            "hint": "Explain the algorithm, its time complexity, and the crucial precondition.",
            "difficulty": "Easy",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "What is the difference between DFS and BFS? When would you use each?",
            "keywords": ["traversal", "stack", "queue", "use case", "depth", "breadth"],
            "hint": "Compare the two approaches and give practical examples for when to use each.",
            "difficulty": "Medium",
            "target_role": "Backend Developer",
        },
        {
            "question": "How would you approach solving a problem you've never seen before?",
            "keywords": ["understand", "break down", "pattern", "implement", "test"],
            "hint": "Walk through your problem-solving process step by step.",
            "difficulty": "Hard",
            "target_role": "Software Engineer",
        },
        {
            "question": "Explain hash tables and the concept of collision handling.",
            "keywords": ["hash function", "collision", "chaining", "open addressing"],
            "hint": "Define hash tables, explain collisions, and discuss different resolution strategies.",
            "difficulty": "Medium",
            "target_role": "Systems Engineer",
        },
        {
            "question": "How would you implement a LRU (Least Recently Used) cache?",
            "keywords": ["cache", "LRU", "design", "efficiency"],
            "hint": "Design the data structure, explain operations, and discuss time complexity.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "What are sorting algorithms and their time/space complexities?",
            "keywords": ["sorting", "quicksort", "mergesort", "complexity", "stability"],
            "hint": "Compare different sorting algorithms and when to use each.",
            "difficulty": "Medium",
            "target_role": "Software Engineer",
        },
        {
            "question": "Explain dynamic programming and provide a real-world example.",
            "keywords": ["memoization", "overlapping subproblems", "optimization", "recursion"],
            "hint": "Explain the concept and solve a classic DP problem like coin change or knapsack.",
            "difficulty": "Hard",
            "target_role": "Full Stack Developer",
        },
    ],
    "DBMS": [
        {
            "question": "What is normalization and why is it important?",
            "keywords": ["redundancy", "integrity", "normal forms", "design"],
            "hint": "Explain the goal of normalization and how it improves database quality.",
            "difficulty": "Medium",
            "target_role": "Backend Developer",
        },
        {
            "question": "What is the difference between SQL joins?",
            "keywords": ["inner join", "left join", "right join", "matching records"],
            "hint": "Use a simple example to explain how each join behaves.",
            "difficulty": "Easy",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "How do indexes improve database performance?",
            "keywords": ["search speed", "lookup", "tradeoff", "write cost"],
            "hint": "Talk about faster reads and the cost of maintaining indexes during updates.",
            "difficulty": "Medium",
            "target_role": "Data Scientist",
        },
        {
            "question": "What is ACID and why does it matter in databases?",
            "keywords": ["atomicity", "consistency", "isolation", "durability", "transaction"],
            "hint": "Explain each property and its role in database reliability.",
            "difficulty": "Medium",
            "target_role": "Backend Developer",
        },
        {
            "question": "What is the N+1 query problem and how do you solve it?",
            "keywords": ["query", "loop", "optimization", "join", "eager loading"],
            "hint": "Describe the problem with an example and explain the solution approaches.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "Explain the difference between NoSQL and SQL databases.",
            "keywords": ["relational", "document", "scalability", "schema", "consistency"],
            "hint": "Compare structure, scalability, use cases, and trade-offs.",
            "difficulty": "Medium",
            "target_role": "DevOps Engineer",
        },
        {
            "question": "What is a database transaction and how do you manage them?",
            "keywords": ["transaction", "commit", "rollback", "isolation level", "deadlock"],
            "hint": "Explain transaction lifecycle and isolation levels.",
            "difficulty": "Medium",
            "target_role": "Systems Engineer",
        },
        {
            "question": "How would you optimize a slow database query?",
            "keywords": ["query plan", "indexes", "query optimization", "profiling"],
            "hint": "Walk through your debugging process and optimization techniques.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "What is database sharding and when would you use it?",
            "keywords": ["sharding", "partition", "scalability", "distributed", "consistency"],
            "hint": "Explain sharding strategy, trade-offs, and when it's necessary.",
            "difficulty": "Hard",
            "target_role": "Systems Engineer",
        },
        {
            "question": "Explain database backup and disaster recovery strategies.",
            "keywords": ["backup", "recovery", "replication", "redundancy", "RTO", "RPO"],
            "hint": "Discuss backup types and recovery strategies for business continuity.",
            "difficulty": "Medium",
            "target_role": "DevOps Engineer",
        },
    ],
    "Operating Systems": [
        {
            "question": "What is the difference between a process and a thread?",
            "keywords": ["memory space", "execution", "overhead", "concurrency"],
            "hint": "Compare resource sharing, performance, and use cases.",
            "difficulty": "Easy",
            "target_role": "Systems Engineer",
        },
        {
            "question": "What is deadlock and how can it be prevented?",
            "keywords": ["resources", "circular wait", "prevention", "avoidance"],
            "hint": "Define deadlock, list the causes, and explain at least one prevention strategy.",
            "difficulty": "Hard",
            "target_role": "Systems Engineer",
        },
        {
            "question": "Why is CPU scheduling important?",
            "keywords": ["utilization", "response time", "fairness", "algorithms"],
            "hint": "Connect scheduling to system performance and user experience.",
            "difficulty": "Medium",
            "target_role": "Backend Developer",
        },
        {
            "question": "What is virtual memory and why do we need it?",
            "keywords": ["memory management", "paging", "swapping", "abstraction"],
            "hint": "Explain the concept and how it allows programs to use more memory than physically available.",
            "difficulty": "Medium",
            "target_role": "Systems Engineer",
        },
        {
            "question": "Explain the concept of semaphores and mutexes.",
            "keywords": ["synchronization", "semaphore", "mutex", "race condition", "locking"],
            "hint": "Define both, explain their differences, and their use in preventing race conditions.",
            "difficulty": "Medium",
            "target_role": "Backend Developer",
        },
        {
            "question": "What is the difference between user mode and kernel mode?",
            "keywords": ["privilege level", "context switch", "system call", "protection"],
            "hint": "Explain the purpose of each mode and why the distinction exists.",
            "difficulty": "Medium",
            "target_role": "Systems Engineer",
        },
        {
            "question": "How does memory paging work in virtual memory systems?",
            "keywords": ["page table", "page fault", "TLB", "replacement", "fragmentation"],
            "hint": "Explain the page replacement algorithm and TLB's role.",
            "difficulty": "Hard",
            "target_role": "Systems Engineer",
        },
        {
            "question": "Explain the various states of a process and state transitions.",
            "keywords": ["process state", "ready", "running", "blocked", "transition"],
            "hint": "Describe each state and the conditions that cause transitions.",
            "difficulty": "Medium",
            "target_role": "Backend Developer",
        },
        {
            "question": "What is context switching and what are its costs?",
            "keywords": ["context switch", "overhead", "performance", "cache", "TLB"],
            "hint": "Explain what happens during context switch and its performance implications.",
            "difficulty": "Hard",
            "target_role": "Systems Engineer",
        },
        {
            "question": "Describe different CPU scheduling algorithms and their trade-offs.",
            "keywords": ["FCFS", "Round Robin", "Priority", "SJF", "fairness", "throughput"],
            "hint": "Compare different scheduling algorithms with examples and metrics.",
            "difficulty": "Hard",
            "target_role": "Systems Engineer",
        },
    ],
    "Projects": [
        {
            "question": "Explain one of your projects and your contribution.",
            "keywords": ["problem", "architecture", "your role", "result"],
            "hint": "Clearly separate the project goal, the tech stack, your work, and the final outcome.",
            "difficulty": "Medium",
            "target_role": "Software Engineer",
        },
        {
            "question": "What was the toughest bug you solved in a project?",
            "keywords": ["debugging", "root cause", "fix", "learning"],
            "hint": "Show your debugging process instead of only describing the final fix.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "If you had more time, how would you improve your project?",
            "keywords": ["scalability", "security", "user experience", "testing"],
            "hint": "Demonstrate product thinking by mentioning realistic next improvements.",
            "difficulty": "Medium",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "Tell me about a project where you learned something new.",
            "keywords": ["learning", "technology", "challenge", "growth"],
            "hint": "Focus on the learning journey and how you approached something unfamiliar.",
            "difficulty": "Easy",
            "target_role": "Software Engineer",
        },
        {
            "question": "How do you approach testing and quality assurance in your projects?",
            "keywords": ["testing", "quality", "automation", "bug prevention"],
            "hint": "Discuss unit tests, integration tests, and your QA strategy.",
            "difficulty": "Medium",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "Describe a project where you worked with a team. What was your role?",
            "keywords": ["teamwork", "collaboration", "responsibility", "coordination"],
            "hint": "Highlight your role, communication, and contribution to team success.",
            "difficulty": "Medium",
            "target_role": "Software Engineer",
        },
        {
            "question": "What tools, frameworks, and technologies do you use regularly?",
            "keywords": ["tech stack", "frameworks", "tools", "experience", "expertise"],
            "hint": "List specific technologies and explain why you prefer them.",
            "difficulty": "Easy",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "How did you handle performance optimization in your projects?",
            "keywords": ["optimization", "profiling", "bottleneck", "efficiency", "metrics"],
            "hint": "Describe performance issues you found and solutions you implemented.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "Tell me about a project that failed or didn't meet expectations.",
            "keywords": ["failure", "lesson", "responsibility", "recovery", "improvement"],
            "hint": "Be honest, take responsibility, and explain what you learned.",
            "difficulty": "Medium",
            "target_role": "Software Engineer",
        },
        {
            "question": "How do you approach documentation and code maintainability?",
            "keywords": ["documentation", "code quality", "maintainability", "comments", "standards"],
            "hint": "Discuss your practices for making code understandable for future developers.",
            "difficulty": "Medium",
            "target_role": "Full Stack Developer",
        },
    ],
    "System Design": [
        {
            "question": "How would you design a URL shortener?",
            "keywords": ["unique id", "database", "scalability", "redirection"],
            "hint": "Cover the core components, data flow, and how the system scales.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "How would you design a chat application?",
            "keywords": ["real time", "websocket", "storage", "delivery"],
            "hint": "Focus on message flow, online users, persistence, and reliability.",
            "difficulty": "Hard",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "How would you design an online coding platform?",
            "keywords": ["submission", "sandbox", "test cases", "queue"],
            "hint": "Explain how code is received, executed safely, and evaluated at scale.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "How would you design a video streaming service like YouTube?",
            "keywords": ["storage", "streaming", "caching", "CDN", "scalability"],
            "hint": "Consider video storage, streaming protocols, caching, and geographic distribution.",
            "difficulty": "Hard",
            "target_role": "Systems Engineer",
        },
        {
            "question": "How would you design an e-commerce platform?",
            "keywords": ["inventory", "payments", "scalability", "reliability", "database"],
            "hint": "Cover product catalog, cart, checkout, and handling high traffic.",
            "difficulty": "Hard",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "How would you design a distributed cache system like Redis?",
            "keywords": ["cache", "distributed", "consistency", "eviction", "performance"],
            "hint": "Discuss cache strategies, consistency models, and scalability.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "How would you design a social media feed?",
            "keywords": ["feed generation", "ranking", "scalability", "real-time", "notifications"],
            "hint": "Explain how to efficiently generate and deliver personalized feeds.",
            "difficulty": "Hard",
            "target_role": "Full Stack Developer",
        },
        {
            "question": "How would you design a cloud storage system like Google Drive?",
            "keywords": ["storage", "sync", "versioning", "sharing", "scalability"],
            "hint": "Discuss file sync, conflict resolution, and distributed storage.",
            "difficulty": "Hard",
            "target_role": "Systems Engineer",
        },
        {
            "question": "How would you design a search engine?",
            "keywords": ["indexing", "ranking", "crawling", "query processing", "scalability"],
            "hint": "Cover web crawling, indexing, ranking algorithms, and serving results.",
            "difficulty": "Hard",
            "target_role": "Backend Developer",
        },
        {
            "question": "How would you design a rate limiting service?",
            "keywords": ["rate limiting", "throttling", "distributed", "algorithms", "performance"],
            "hint": "Explain rate limiting algorithms and how to implement at scale.",
            "difficulty": "Hard",
            "target_role": "Systems Engineer",
        },
    ],
    "Cybersecurity": [
        {
            "question": "What is the CIA triad and why is it important in cybersecurity?",
            "keywords": ["confidentiality", "integrity", "availability", "security principles"],
            "hint": "Explain each component of the triad and how they form the foundation of information security.",
            "difficulty": "Easy",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "Explain the difference between encryption and hashing.",
            "keywords": ["encryption", "hashing", "reversible", "irreversible", "passwords"],
            "hint": "Compare how encryption can be reversed while hashing cannot, and give practical examples.",
            "difficulty": "Medium",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "What is a firewall and how does it work?",
            "keywords": ["firewall", "network security", "packet filtering", "rules", "traffic"],
            "hint": "Describe the purpose of firewalls and explain different types (hardware, software, next-gen).",
            "difficulty": "Easy",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "Describe SQL injection and how to prevent it.",
            "keywords": ["SQL injection", "web security", "input validation", "prepared statements", "OWASP"],
            "hint": "Explain how attackers exploit SQL injection and discuss prevention techniques like parameterized queries.",
            "difficulty": "Medium",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "What is cross-site scripting (XSS) and how can it be mitigated?",
            "keywords": ["XSS", "web security", "script injection", "sanitization", "CSP"],
            "hint": "Describe stored, reflected, and DOM-based XSS, then explain prevention methods.",
            "difficulty": "Medium",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "Explain the principle of least privilege and why it's important.",
            "keywords": ["least privilege", "access control", "permissions", "security", "minimization"],
            "hint": "Define the principle and give examples of how it reduces security risks in systems.",
            "difficulty": "Easy",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "What is two-factor authentication (2FA) and how does it improve security?",
            "keywords": ["2FA", "authentication", "factors", "password", "biometrics"],
            "hint": "Explain the different authentication factors and how 2FA provides better protection than passwords alone.",
            "difficulty": "Easy",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "What is a VPN and why is it used for security?",
            "keywords": ["VPN", "encryption", "tunnel", "privacy", "remote access"],
            "hint": "Describe how VPNs create secure connections and their common use cases.",
            "difficulty": "Medium",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "How would you respond to a security breach in an organization?",
            "keywords": ["incident response", "breach", "containment", "forensics", "recovery"],
            "hint": "Outline the steps in incident response: detection, containment, eradication, recovery, and lessons learned.",
            "difficulty": "Hard",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "What are common password policies and why are they important?",
            "keywords": ["password policy", "complexity", "expiration", "brute force", "best practices"],
            "hint": "Discuss password requirements, rotation policies, and how they prevent common attacks.",
            "difficulty": "Easy",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "Explain the concept of social engineering and give examples.",
            "keywords": ["social engineering", "phishing", "pretexting", "human factor", "awareness"],
            "hint": "Define social engineering and describe common techniques like phishing, baiting, and pretexting.",
            "difficulty": "Medium",
            "target_role": "Cybersecurity Analyst",
        },
        {
            "question": "What is a DDoS attack and how can it be mitigated?",
            "keywords": ["DDoS", "denial of service", "traffic", "amplification", "mitigation"],
            "hint": "Explain how DDoS attacks work and discuss prevention strategies like rate limiting and CDNs.",
            "difficulty": "Medium",
            "target_role": "Cybersecurity Analyst",
        },
    ],
}



def get_questions(category: str) -> list[dict]:
    return QUESTION_BANK.get(category, [])
